export const SITE = {
  name: "workwithme.lol",
  wordmark: "workwithme.lol",
  origin: "https://workwithme.lol",
  tagline: "How high are you willing to go?",
  deck: "The professional leaderboard where money talks. Bid for your spot. Get seen. Get outbid. Do it again.",
  cta: "GET ON THE BOARD",
  micro: "Higher bid = higher rank. That's basically it.",
  footer: "Money buys placement, not quality.",
  share: "I'm #37 on workwithme.lol. Think I deserve to be lower?",
  joinLead: "Identify yourself and put a number on it.",
  joinEntry: "New spots start at $2. Paying less than #1 still puts you on the board wherever that bid ranks.",
  joinRepeat: "Already on the list? Same identity, higher bid.",
  joinRule: "Higher bid = higher rank. Money buys placement, not quality.",
} as const;
